### PR TITLE
much more flexible and cleaner action init

### PR DESCRIPTION
**Pull request by marc-hanheide**
This is my attempt to automate the initialisation etc and making it more robust. Last year we failed two tasks because of last-minute errors in this file, which in the past meant, one single exception and the whole thing stepped out. Now it searches all python files in the same directory as `init_actions` is in and checks if they have an `init` and `quit` function. If they do, they are called, but in a `try` to make sure the rest is still initialised if one action should fail for whatever obscure reason. The same for the behaviours, which might also fail for one or another reason (e.g. that when you test locally, some simply don't exist). Also, the whole thing is much cleaner and should only ever be edited at the beginning if need be, with these two variables:

```
# list all files in here you don't want autoloaded
# (without .py at the end, just the name)
blacklisted_actions = ['personhere']

# this is a list of tuples (Proxy, Subscriber) to 
# initialise services at the beginning
behaviours = [
    ('ALFaceDetection', 'Face_Behavior'),
    ('ALFaceCharacteristics', 'Char_Behavior'),
    ('ALPeoplePerception', 'People_Behavior'),
    ('ALSittingPeopleDetection', 'Sitting_Behavior'),
    ('ALSoundLocalization', 'Sound_Behavior'),
    ('ALMotion', 'Motion_Behavior'),
    ('ALWavingDetection', 'Waving_Behavior'),
    ('ALAnimationPlayer', None)
]
```

Let me know if you see any issue with it, worked very well for me in tests.

### CODE REVIEW

**Comment by marc-hanheide** [comment]
I made you all reviewers to make sure you checked and understood what I was trying to do here ;-)

**Comment by iocchi** [comment]
Just looked at the code. It seems correct. I can test it tonight.

**Comment by francescodelduchetto** [comment]
I checked this on pepper and it works properly ;-)

**Comment by marc-hanheide** [comment]
OK, before you all create more conflicts with this branch, I'm going to merge it as @francescodelduchetto confirmed it working.

**Pull request merged**
