### PR TITLE
adding navigate to action

### PR DESCRIPTION
**Pull request by Jailander**
Needs Testing!!!

### CODE REVIEW

**Comment by sergimolina** [comment]
@marc-hanheide can you check this PR it got messed up (it's @Jailander from sergis pc)

**Comment by marc-hanheide** [comment]
@Jailander what happened here? This contains a lot of changes that would revert to versions of files you shoudn't have touched! We can't merge it as it is! I will close it, so that nobody merges it accidently.

**Comment by marc-hanheide** [comment]
@Jailander can you make sure you rebase this on the head? I really don't understand how this could have happened? Did you manually copy anything over at some point?

**Comment by Jailander** [comment]
I am not sure if it was me pulling from a different branch maybe? I can try to fix tonight

**Comment by marc-hanheide** [comment]
Even then it shouldn't look like this. Anyway... I can try to fix it... All we want is commit https://github.com/LCAS/spqrel_tools/pull/35/commits/14a4baa1496ac63904541336a79ca8950daf9b64 I think, which introduced the config manager. and then I'll have a look for the commits of the navigation.

**Comment by marc-hanheide** [comment]
so, 4afafd0696d3a37a465900b34d781ad6050e9266 should be the one for the nav action. So, I'll just cherry-pick those, ok?

**Comment by Jailander** [comment]
Hi yes that is perfect sorry didn't see this last night, mybparents flight was very late.

**Pull request closed without merging**
